language: java
jdk:
  - openjdk11
branches:
  only:
    - master
# Travis CI 서버의 Home
cache:
  directories:
       - '$HOME/.m2/repository'
       - '$HOME/.gradle'

script: "./gradlew clean assemble"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - jjimini98@naver.com

출처: https://acet.pe.kr/909 [Story Of ace-T]